--INSERT INTO user (email, password_hash, role)
--VALUES ('demo@localhost', '$2a$10$ebyC4Z5WtCXXc.HGDc1Yoe6CLFzcntFmfse6/pTj7CeDY5I05w16C', 'ADMIN');
-- create table person (
--    id integer not null,
--    name varchar(255) not null,
--    location varchar(255),
--    birth_date timestamp,
--    primary key(id)
-- );

-- INSERT
--   INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE )
-- VALUES(10001,  'Ranga', 'Hyderabad',sysdate());
--
-- INSERT
--   INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE )
-- VALUES(10002,  'James', 'New York',sysdate());
--
-- INSERT
--   INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE )
-- VALUES(10003,  'Pieter', 'Amsterdam',sysdate());